<a href="https://colab.research.google.com/github/pandeygargi847-ai/AI-ML-INTERNSHIP-/blob/main/Politics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import plotly.graph_objects as go
import plotly.express as  xp

LOADING DATA

In [4]:
modi =pd.read_csv("/content/modi_reviews.csv")
rahul =pd.read_csv("/content/rahul_reviews.csv")

In [5]:
modi.head()

,Unnamed: 0,User,Tweet
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...
3,3,TheNirbhay1,PM Modi creates a new record of being the only...
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...

In [6]:
rahul.head()

,Unnamed: 0,User,Tweet
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ..."
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...

In [7]:
modi.shape

(25688, 3)

In [8]:
rahul.shape

(14261, 3)

In [9]:
TextBlob(modi['Tweet'][10]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [10]:
TextBlob(rahul['Tweet'][2]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [11]:
modi['Tweet']=modi['Tweet'].astype(str)
rahul['Tweet']=rahul['Tweet'].astype(str)

def findpolarity(review):
  return TextBlob(review).sentiment.polarity

In [12]:
modi['Polarity']=modi['Tweet'].apply(findpolarity)
rahul['Polarity']=rahul['Tweet'].apply(findpolarity)

In [13]:
modi.head()

,Unnamed: 0,User,Tweet,Polarity
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788

In [14]:
rahul.head()

,Unnamed: 0,User,Tweet,Polarity
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...,0.218750
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...,0.000000
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...,0.000000
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ...",0.320000
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...,-0.166667

In [15]:
modi['Label']=np.where(modi['Polarity']>0,'Positive','Negative')
modi['Label'][modi['Polarity']==0]='Neutral'

rahul['Label']=np.where(rahul['Polarity']>0,'Positive','Negative')
rahul['Label'][rahul['Polarity']==0]='Neutral'

/tmp/ipykernel_1585/3874777552.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  modi['Label'][modi['Polarity']==0]='Neutral'
/tmp/ipykernel_1585/3874777552.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modi['Label'][modi['Polarity']==0]='Neutral'
/tmp/ipykernel_1585/3874777552.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  rahul['Label'][rahul['Polarity']==0]='Neutral'
/tmp/ipykernel_1585/3874777552.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rahul['Label'][rahul['Polarity']==0]='Neutral'

In [16]:
modi

,Unnamed: 0,User,Tweet,Polarity,Label
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000,Positive
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000,Positive
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121,Positive
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788,Positive
...,...,...,...,...,...
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...,0.000000,Neutral
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...,0.209524,Positive
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...,-0.700000,Negative
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ...",0.000000,Neutral
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ...",-0.213542,Negative

In [17]:
neutral_modi=modi[modi['Polarity']==0.000]
remove_neutral_modi=modi['Polarity'].isin(neutral_modi['Polarity'])
modi.drop(modi[remove_neutral_modi].index,inplace=True)

In [18]:
modi.shape

(17482, 5)

In [19]:
rahul.shape

(14261, 5)

In [20]:
# making row count to 9000
# for modi
np.random.seed(10)
remove_n=8482
drop_indices=np.random.choice(modi.index,remove_n,replace=False)
df_modi=modi.drop(drop_indices)

In [21]:
df_modi.shape

(9000, 5)

In [22]:
# making row count to 9000
# for rahul
np.random.seed(10)
remove_n=8482
drop_indices=np.random.choice(rahul.index,remove_n,replace=False)
df_rahul=rahul.drop(drop_indices)

In [23]:
df_rahul.shape

(5779, 5)

prediction for election

In [24]:
modi_count = df_modi.groupby('Label').count()
modi_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative        2629  2629   2629      2629
Positive        6371  6371   6371      6371

In [32]:
nef_modi = (modi_count['Polarity'].loc['Negative'] / 1000) * 100
pos_modi = (modi_count['Polarity'].loc['Positive'] / 1000) * 100

In [33]:
rahul_count =  df_rahul.groupby('Label').count()
nef_rahul = (rahul_count['Polarity'].loc['Negative'] / 1000) * 100
pos_rahul = (rahul_count['Polarity'].loc['Positive'] / 1000) * 100

In [29]:
rahul_count =  df_rahul.groupby('Label').count()
rahul_count

          Unnamed: 0  User  Tweet  Polarity
Label
Negative        1263  1263   1263      1263
Neutral         1978  1978   1978      1978
Positive        2538  2538   2538      2538

In [31]:
politicians = ['Modi', 'Rahul']
neg_list = [nef_modi, nef_rahul]
pos_list = [pos_modi, pos_rahul]

fig = go.Figure(data=[
    go.Bar(name='Negative', x=politicians, y=neg_list),
    go.Bar(name='Positive', x=politicians, y=pos_list)
])
# Change the bar mode
fig.update_layout(barmode='group')
fig.show()