<a href="https://colab.research.google.com/github/pandeygargi847-ai/AI-ML-INTERNSHIP-/blob/main/Python_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello World");
print("Gargi Pandey");

hello World
Gargi Pandey

In [ ]:
name = ("Gargi Pandey")
print(name)

Gargi Pandey

In [ ]:
full_name =("Gargi Pandey")
print(full_name)

Gargi Pandey

In [ ]:
name = ("Gargi Pandey")
Address = ("B-928 Sector B Mahanagar Lucknow")
college = ("Shri Ramswaroop Memorial College of Engineering and Management")
print(name)
print(Address)
print(college)

Gargi Pandey
B-928 Sector B Mahanagar Lucknow
Shri Ramswaroop Memorial College of Engineering and Management

In [ ]:
a = 20
b = 40
print(a+b)
print(a*b)
print(a-b)
print(a/b)
print(a%b)
print(a**b)
print(type(a))
print(type(b))

60
800
-20
0.5
20
10995116277760000000000000000000000000000000000000000
<class 'int'>
<class 'int'>

In [ ]:
name = input("Enter your name")
print(name)

age  = int(input("Enter your age"))
Marks = float(input("Enter the marks scored"))

Enter your nameGargi Pandey
Gargi Pandey
Enter your age19
Enter the marks scored98.56

In [ ]:
name = input("Enter your name")
print(name)
age = int(input("Enter your age"))
print(age)
department = input("Enter your department")
print(department)
college = input("Enter the name of the college")
print(college)
Phoneno = int(input("Enter the phone number"))
print(Phoneno)

Enter your nameGargi Pandey
Gargi Pandey
Enter your age19
19
Enter your departmentAI & ML
AI & ML
Enter the name of the collegeSRMCEM
SRMCEM
Enter the phone number6387781071
6387781071

In [ ]:
a = "10"
print(int(a)+5)

15

In [ ]:
a = "10.55"
print(int(a))

ValueError: invalid literal for int() with base 10: '10.55'

In [ ]:
a = "10.55"
print(int(float(a))) #type casting

10

In [ ]:
name = "Gargi Pandey"
print(name.upper())

GARGI PANDEY

In [ ]:
name = "gargi pandey"
print(name.replace("pandey", "Singh"))

gargi Singh

In [ ]:
age = 40
if age >= 18 & age <60:
  print("Eligible")
else:
  print("not eligible")

Eligible

In [ ]:
marks = 95
rank = 40000

if marks > 90 or rank < 50000:
  print("eligible")
else:
  print("not eligible")

eligible

In [ ]:
marks = int(input("Enter the marks"))
rank = int(input("Enter the rank"))
if marks > 90 or rank < 50000:
  print("eligible")
else:
  print("not eligible")

Enter the marks95
Enter the rank80000
eligible

In [ ]:
age = int(input("Enter the age"))
if age > 60:
  print("senior citizen")
elif age <= 60 and age > 35:
  print("Middle age")
elif age <= 35 and age > 18:
  print("Youth")
else:
  print("kids")

Enter the age8
kids

In [ ]:

marks_str = input("Enter the marks")
try:
    marks = int(marks_str)
    if marks > 90:
        print("Grade A")
    elif marks > 80:
        print("Grade B")
    elif marks > 70:
        print("Grade C")
    elif marks > 60:
        print("Grade D")
    else:
        print("Fail")
except ValueError:
    print("Invalid input. Please enter a valid number for marks.")

Enter the marks84
Grade B

In [ ]:
number_input = input("Enter the number")
n = int(number_input) # This line will raise ValueError if input is not an integer
if n % 5 == 0:
  print("divisible by 5")
else:
  print("not divisible by 5")

Enter the number25
divisible by 5

In [ ]:
number = int(input("Enter the number"))
if number % 3 == 0:
  print("divisible by 3")
else:
  print("not divisible by 3")

Enter the number39
divisible by 3

In [ ]:
n = int(input("Enter the number"))
if n % 3 == 0 and n % 5==0:
  print("divisible by both 3 and 5")
else:
  print("not divisible")

Enter the number25
not divisible

In [ ]:
num = int(input("Enter the number"))
if num% 3== 0  and num%5==0:
  print("divisible by both 3 and 5")
elif(num%3==0):
  print("divisible by 3")
elif(num%5==0):
  print("divisible by 5")
else:
  print("divisible by none of them")

Enter the number36
divisible by 3

In [ ]:
balance = input("Enter the amount of balance")
withdraw = input("Enter the amount to be withdrawn")
if withdraw <=balance:
  print("withdrawn")

else:
  print("Not possible")

Enter the amount of balance5000
Enter the amount to be withdrawn6000
Not possible

In [ ]:
password = input("Enter the password")
if password == "Gargipandey":
  print("Accessed")
else:
  print("Accessed denied")

Enter the passwordgargi
Accessed denied

In [ ]:
password = input("Enter the password")
if password == "Gargipandey":
  print("Accessed")
else:
    print("Accessed denied")

Enter the passwordGargipandey
Accessed

In [ ]:
num = input("Enter the number: ")
try:
  n = int(num)
  if n >= 0 and n <= 9:
    print(f"{n} is a single-digit number.")
  elif n >= 10 and n <= 99:
    print(f"{n} is a double-digit number.")
  else:
    print(f"{n} is neither a single-digit nor a double-digit number.")
except ValueError:
  print("Invalid input. Please enter a valid integer.")

Enter the number: 56
56 is a double-digit number.

In [ ]:
for i in range(10):
   print(i)

0
1
2
3
4
5
6
7
8
9

In [ ]:
for i in range(5, 51, 5):
 print(i)

5
10
15
20
25
30
35
40
45
50

In [ ]:
for i in range(6, 61, 6):
  print(i)

6
12
18
24
30
36
42
48
54
60

In [ ]:
for i in range(7, 71, 7):
  print(i)

7
14
21
28
35
42
49
56
63
70

In [ ]:
for i in range(10, 0, -1):
  print(i)

10
9
8
7
6
5
4
3
2
1

In [ ]:
for i in range(50, 4, -5):
  print(i)

50
45
40
35
30
25
20
15
10
5

In [ ]:
for i in range(60, 5, -6):
  print(i)

60
54
48
42
36
30
24
18
12
6

In [ ]:
for i in range(5,51,5):
  print(i)
  if i == 35:
    break

5
10
15
20
25
30
35

In [ ]:
for i in range(5,51,5):
  print(i)
  if i == 20:
    break

5
10
15
20

In [ ]:
for i in range(6, 61, 6):
  if i == 36:
    continue
  print(i)

6
12
18
24
30
42
48
54
60

In [ ]:
a = 12
b = 11
a,b = b,a
print(a)
print(b)

11
12

In [ ]:
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

add = a + b
print("Addition:", add)

sub = a - b
print("Subtraction:", sub)

multiply = a * b
print("Multiplication:", multiply)

modulo = a % b
print("Modulo:", modulo)

division = a/b
print("Division:", division)

Enter the first number: 8
Enter the second number: 4
Addition: 12
Subtraction: 4
Multiplication: 32
Modulo: 0
Division: 2.0

In [ ]:
name = "Gargi"
print(name[2])
print(name[0:2]) #slicing of strings
na = "12348976"
print(na[3:5])

r
Ga
48

In [ ]:
name = "I love to read books"
print(name[0:7])
print(name[2:9])
print(name[5:10])
rev  = print(name[::-1])

I love
love to
e to
skoob daer ot evol I

In [ ]:
name ="Harshit"
print(" Harshit " *100) #repetition

 Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit  Harshit

In [ ]:
#concatination
name= "Gargi"
title = "Pandey"
print(name + "@" + title)

Gargi@Pandey
False

In [ ]:
name = "Anjali"
print(name[1])
print(name[-3])
print(name[0:2]) #slicing
print(name[0:9])

n
a
An
Anjali

In [ ]:
#concatination
name = "Anshuman"
title = "Pandey"
print(name+ "_" + title)

Anshuman_Pandey

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Zomato-data-.csv')

In [ ]:
# one dimensional data
import pandas as pd
marks = pd.Series([85,90,78,95])
print(marks)

0    85
1    90
2    78
3    95
dtype: int64

In [ ]:
import pandas as pd

#2- d data


student = {
    "Name":["Rahul", "Amit", "Priya"],
    "Age":[20,21,19],
    "Marks":[80,90,95]
}
df = pd.DataFrame(student)
print(df)

    Name  Age  Marks
0  Rahul   20     80
1   Amit   21     90
2  Priya   19     95

In [ ]:
df = pd.read_csv('/content/Zomato-data-.csv')

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df.sample()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
94,Nandhini Deluxe,No,No,2.6/5,283,600,Dining

In [ ]:
df.shape

(148, 7)

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [ ]:
df.dtypes

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [ ]:
df.dtypes

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [ ]:
df['approx_cost(for two people)'].describe()

count    148.000000
mean     418.243243
std      223.085098
min      100.000000
25%      200.000000
50%      400.000000
75%      600.000000
max      950.000000
Name: approx_cost(for two people), dtype: float64

In [ ]:
df["name"] #selecting single column data

0                      Jalsa
1             Spice Elephant
2            San Churro Cafe
3      Addhuri Udupi Bhojana
4              Grand Village
               ...
143         Melting Melodies
144          New Indraprasta
145             Anna Kuteera
146                   Darbar
147            Vijayalakshmi
Name: name, Length: 148, dtype: object

In [ ]:
df[["name","online_order"]] #selecting multiple columns data

                      name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [ ]:
df.sort_values("votes") #ascending order
df["votes"]
"""
df.sort_values("votes", ascending=False) #descending order

df.sort_values(["Department", "Salary"]) #multiple column sorting

df["Bonus"]= df["Salary"]*0.18 #adding new column

df["Total Salary"]= df["Salary"]+df["Bonus"] #adding new column
"""

'\ndf.sort_values("votes", ascending=False) #descending order\n\ndf.sort_values(["Department", "Salary"]) #multiple column sorting\n\ndf["Bonus"]= df["Salary"]*0.18 #adding new column\n\ndf["Total Salary"]= df["Salary"]+df["Bonus"] #adding new column\n'

In [ ]:
import pandas as pd

data = {
    "Emp_ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman","Neha","Rahul","Priya","Karan",
             "Simran","Mohit","Anjali","Vikas","Pooja"],
    "Age": [24,25,23,28,30,26,27,24,29,25],
    "Department": ["HR","IT","Sales","IT","HR",
                   "Finance","Sales","IT","Finance","HR"],
    "Salary": [35000,50000,45000,60000,38000,
               55000,47000,62000,58000,40000],
    "City": ["Delhi","Lucknow","Noida","Delhi","Jaipur",
             "Noida","Lucknow","Delhi","Jaipur","Delhi"]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
import pandas as pd
data = {
    "Emp_ID" : [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Aman", "Neha", "Rahul", "Priya", "Karan", "Simran", "Mohit", "Anjali", "Vikas", "Pooja"],
    "Age": [24, 25, 23, 28, 30, 26, 27, 24, 29, 25],
    "Department": ["HR", "IT", "Sales", "IT", "HR", "Finance", "Sales", "IT", "Finance", "HR"],
    "Salary": [35000, 50000, 45000, 60000, 30000, 25000, 47000, 62000, 58000, 40000],
    "City": ["Delhi", "Lucknow", "Noida", "Delhi", "Jaipur", "Noida", "Lucknow", "Delhi", "Jaipur", "Delhi"]
    }
df = pd.DataFrame(data)
print(df)

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   30000   Jaipur
5     106  Simran   26    Finance   25000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df.head()

   Emp_ID   Name  Age Department  Salary     City
0     101   Aman   24         HR   35000    Delhi
1     102   Neha   25         IT   50000  Lucknow
2     103  Rahul   23      Sales   45000    Noida
3     104  Priya   28         IT   60000    Delhi
4     105  Karan   30         HR   38000   Jaipur

In [ ]:
df.tail()

   Emp_ID    Name  Age Department  Salary     City
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df.sample()

   Emp_ID  Name  Age Department  Salary     City
1     102  Neha   25         IT   50000  Lucknow

In [ ]:
df.shape

(10, 6)

In [ ]:
df.columns

Index(['Emp_ID', 'Name', 'Age', 'Department', 'Salary', 'City'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
 5   City        10 non-null     object
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [ ]:
df.describe()

          Emp_ID        Age        Salary
count   10.00000  10.000000     10.000000
mean   105.50000  26.100000  49000.000000
std      3.02765   2.330951   9580.071909
min    101.00000  23.000000  35000.000000
25%    103.25000  24.250000  41250.000000
50%    105.50000  25.500000  48500.000000
75%    107.75000  27.750000  57250.000000
max    110.00000  30.000000  62000.000000

In [ ]:
df.dtypes

Emp_ID         int64
Name          object
Age            int64
Department    object
Salary         int64
City          object
dtype: object

In [ ]:
df["Name"]

0      Aman
1      Neha
2     Rahul
3     Priya
4     Karan
5    Simran
6     Mohit
7    Anjali
8     Vikas
9     Pooja
Name: Name, dtype: object

In [ ]:
df[["Name", "Salary"]]

     Name  Salary
0    Aman   35000
1    Neha   50000
2   Rahul   45000
3   Priya   60000
4   Karan   38000
5  Simran   55000
6   Mohit   47000
7  Anjali   62000
8   Vikas   58000
9   Pooja   40000

In [ ]:
df[df["Salary"]>5000]

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
1     102    Neha   25         IT   50000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
3     104   Priya   28         IT   60000    Delhi
4     105   Karan   30         HR   38000   Jaipur
5     106  Simran   26    Finance   55000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
7     108  Anjali   24         IT   62000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
9     110   Pooja   25         HR   40000    Delhi

In [ ]:
df[df["Department"]=="IT"]

   Emp_ID    Name  Age Department  Salary     City
1     102    Neha   25         IT   50000  Lucknow
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df[(df["Salary"] > 5000) & (df["Department"] == "IT")]

   Emp_ID    Name  Age Department  Salary     City
1     102    Neha   25         IT   50000  Lucknow
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df.sort_values("Salary")

   Emp_ID    Name  Age Department  Salary     City
0     101    Aman   24         HR   35000    Delhi
4     105   Karan   30         HR   38000   Jaipur
9     110   Pooja   25         HR   40000    Delhi
2     103   Rahul   23      Sales   45000    Noida
6     107   Mohit   27      Sales   47000  Lucknow
1     102    Neha   25         IT   50000  Lucknow
5     106  Simran   26    Finance   55000    Noida
8     109   Vikas   29    Finance   58000   Jaipur
3     104   Priya   28         IT   60000    Delhi
7     108  Anjali   24         IT   62000    Delhi

In [ ]:
df.sort_values("Salary", ascending = False)

   Emp_ID    Name  Age Department  Salary     City
7     108  Anjali   24         IT   62000    Delhi
3     104   Priya   28         IT   60000    Delhi
8     109   Vikas   29    Finance   58000   Jaipur
5     106  Simran   26    Finance   55000    Noida
1     102    Neha   25         IT   50000  Lucknow
6     107   Mohit   27      Sales   47000  Lucknow
2     103   Rahul   23      Sales   45000    Noida
9     110   Pooja   25         HR   40000    Delhi
4     105   Karan   30         HR   38000   Jaipur
0     101    Aman   24         HR   35000    Delhi

In [ ]:
df["Salary"].max()

62000

In [ ]:
df["Salary"].min()

35000

In [ ]:
df["Salary"].mean()

np.float64(49000.0)